
name: Scans

on:
  pull_request:
  push:

jobs:
  SonarQube-Scan:
    uses: ./sonar-scan.yaml
    secrets:
      sonar_token: ${{ secrets.SONAR_TOKEN }}
      sonar_host_url: ${{ secrets.SONAR_HOST_URL }}
